application: primetime4u
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /task/.*
  script: task.app

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: lxml
  version: "2.3"
- name: ssl
  version: latest